# SBI
has_headers = false
delimiter = "comma"


[exclude]
[[exclude.conditions]]
type = "RecordLen"
content = 1

[[exclude.conditions]]
type = "ColumnDoNotMatchRegex"
[exclude.conditions.content]
column = 0
regex_value='^\d{2}/\d{2}/\d{4}'

[xsv_to_ledger_record.date]
date_format="%d/%m/%Y"
date_regex='\d{2}/\d{2}/\d{4}'
column = 0

[xsv_to_ledger_record.payee]
[xsv_to_ledger_record.payee.xsv_to_entry]
hint_columns = [1]

[xsv_to_ledger_record.target_posting]
[xsv_to_ledger_record.target_posting.account]
[xsv_to_ledger_record.target_posting.account.xsv_to_entry]
hint_columns = [1]

[[xsv_to_ledger_record.target_posting.account.xsv_to_entry.hint_mapping]]
key= "DEBIT   ACHDr NACH00 000000017880 YES BANK"
value= "Expenses:Donations"

[[xsv_to_ledger_record.target_posting.account.xsv_to_entry.hint_mapping]]
key= "jaleelsada|jishaavino"
value= "Expenses:Gifts"

[[xsv_to_ledger_record.target_posting.account.xsv_to_entry.hint_mapping]]
key= "CEMTEX DEP|DEP TFR   NEFT|DEP TFR   PFN"
value= "Income:Zerodha:Divident"

[[xsv_to_ledger_record.target_posting.account.xsv_to_entry.hint_mapping]]
key= "0098047041826 AT 04182|9273105219 AT 04182"
value= "Expenses:UnaccountedExpenses"

[[xsv_to_ledger_record.target_posting.account.xsv_to_entry.hint_mapping]]
key= "INTERES"
value =  "Income:SBI:Interest"

[[xsv_to_ledger_record.target_posting.account.xsv_to_entry.hint_mapping]]
key = "LICPGINEW"
value = "Assets:LongTerm:LIC"

[[xsv_to_ledger_record.target_posting.account.xsv_to_entry.hint_mapping]]
key = "Airtel|Amazon"
value = "Expenses:Utilities"

[[xsv_to_ledger_record.target_posting.account.xsv_to_entry.hint_mapping]]
key = "LOCKER"
value = "Expenses:SBI:Fees"

[xsv_to_ledger_record.target_posting.price.amount]
[xsv_to_ledger_record.target_posting.price.amount.quantity]
[xsv_to_ledger_record.target_posting.price.amount.quantity.xsv_to_entry]
hint_columns = [3]

[xsv_to_ledger_record.target_posting.price.amount.commodity]
[xsv_to_ledger_record.target_posting.price.amount.commodity.xsv_to_entry]
hint_columns = [3]

[[xsv_to_ledger_record.target_posting.price.amount.commodity.xsv_to_entry.hint_mapping]]
key= ".*"
value= "INR"

[xsv_to_ledger_record.target_posting.price.exclude]
[[xsv_to_ledger_record.target_posting.price.exclude.conditions]]
type = "ColumnContainsValue"
[xsv_to_ledger_record.target_posting.price.exclude.conditions.content]
column = 3
value = ""
operation = "equal"


[xsv_to_ledger_record.source_posting]
[xsv_to_ledger_record.source_posting.account]
[xsv_to_ledger_record.source_posting.account.xsv_to_entry]
hint_columns = [1]

[[xsv_to_ledger_record.source_posting.account.xsv_to_entry.hint_mapping]]
key= ".*"
value= "Assets:Bank:SBI:Savings"

[xsv_to_ledger_record.source_posting.price.amount]
[xsv_to_ledger_record.source_posting.price.amount.quantity]
[xsv_to_ledger_record.source_posting.price.amount.quantity.xsv_to_entry]
hint_columns = [4]

[xsv_to_ledger_record.source_posting.price.amount.commodity]
[xsv_to_ledger_record.source_posting.price.amount.commodity.xsv_to_entry]
hint_columns = [4]

[[xsv_to_ledger_record.source_posting.price.amount.commodity.xsv_to_entry.hint_mapping]]
key= ".*"
value= "INR"

[xsv_to_ledger_record.source_posting.price.exclude]
[[xsv_to_ledger_record.source_posting.price.exclude.conditions]]
type = "ColumnContainsValue"
[xsv_to_ledger_record.source_posting.price.exclude.conditions.content]
column = 4
value = ""
operation = "equal"
